{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jianghongkui.lint",
    "module": "lib_lint_client_v4_2",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xpu7ub5i45guplxagemmwqh2i4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib_lint_client_v4_2-1.0.0.jar",
          "url": "lib_lint_client_v4_2-1.0.0.jar",
          "size": 51665,
          "sha512": "3d9161251040c764249e67a7a4fe42279a7559bcef32db9af1f5cb2d11c8aea10ff67561f8e48471f828b92e2e0126e953fc94d3f448eabb5bd49ce75289553f",
          "sha256": "c6d780e95641e3c346598c85b7a36a8ceb179bc65244d936e1f2b59b22429814",
          "sha1": "f6f1abfb600520fd26a653127c9818152620ddf8",
          "md5": "569fbdb0a543cd5d304530f04569e2dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "lib_lint_client_v4_2-1.0.0.jar",
          "url": "lib_lint_client_v4_2-1.0.0.jar",
          "size": 51665,
          "sha512": "3d9161251040c764249e67a7a4fe42279a7559bcef32db9af1f5cb2d11c8aea10ff67561f8e48471f828b92e2e0126e953fc94d3f448eabb5bd49ce75289553f",
          "sha256": "c6d780e95641e3c346598c85b7a36a8ceb179bc65244d936e1f2b59b22429814",
          "sha1": "f6f1abfb600520fd26a653127c9818152620ddf8",
          "md5": "569fbdb0a543cd5d304530f04569e2dc"
        }
      ]
    }
  ]
}
