{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jianghongkui.lint",
    "module": "lib_lint_client_v4_1",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xpu7ub5i45guplxagemmwqh2i4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib_lint_client_v4_1-1.0.0.jar",
          "url": "lib_lint_client_v4_1-1.0.0.jar",
          "size": 47666,
          "sha512": "fd05b5b3f17ec357a797dde42466a37200c3088bacf7d58dccce8a09484ca1c2bff5c869a4b055baf8799b94e7ddfbdcf2bd6907b3695ae9bcc4c0c39b2f9de2",
          "sha256": "6e8384c9b50601518d95a22d9d1404e9183ce9f11e2d19556ca5ef22365cd9d8",
          "sha1": "095cdb1f8fc469066bdc00742b6bfdb2ef31f173",
          "md5": "1851c424d923f1dddb8486e8e4236732"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "lib_lint_client_v4_1-1.0.0.jar",
          "url": "lib_lint_client_v4_1-1.0.0.jar",
          "size": 47666,
          "sha512": "fd05b5b3f17ec357a797dde42466a37200c3088bacf7d58dccce8a09484ca1c2bff5c869a4b055baf8799b94e7ddfbdcf2bd6907b3695ae9bcc4c0c39b2f9de2",
          "sha256": "6e8384c9b50601518d95a22d9d1404e9183ce9f11e2d19556ca5ef22365cd9d8",
          "sha1": "095cdb1f8fc469066bdc00742b6bfdb2ef31f173",
          "md5": "1851c424d923f1dddb8486e8e4236732"
        }
      ]
    }
  ]
}
