{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jianghongkui.lint",
    "module": "lib_lint_client_v3_6",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xpu7ub5i45guplxagemmwqh2i4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib_lint_client_v3_6-1.0.0.jar",
          "url": "lib_lint_client_v3_6-1.0.0.jar",
          "size": 21110,
          "sha512": "d58660e29dabdb62cd0de535d18e2fbba46bdecd5d8a6cd84d690483cb71f6b062a4187a7cf03dd56cb3f02c3784ac23726ffec15fc74412f13e2f2e71d1c80b",
          "sha256": "cb9c72ec7c4484dadf21b40ddf3da4b70c9fc94be32fed97ee34134a6ecb6ed8",
          "sha1": "c67594b95e3706a73c936922342045a1fbd15924",
          "md5": "9c386151138c24558eebe0708ca51fca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "lib_lint_client_v3_6-1.0.0.jar",
          "url": "lib_lint_client_v3_6-1.0.0.jar",
          "size": 21110,
          "sha512": "d58660e29dabdb62cd0de535d18e2fbba46bdecd5d8a6cd84d690483cb71f6b062a4187a7cf03dd56cb3f02c3784ac23726ffec15fc74412f13e2f2e71d1c80b",
          "sha256": "cb9c72ec7c4484dadf21b40ddf3da4b70c9fc94be32fed97ee34134a6ecb6ed8",
          "sha1": "c67594b95e3706a73c936922342045a1fbd15924",
          "md5": "9c386151138c24558eebe0708ca51fca"
        }
      ]
    }
  ]
}
