{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jianghongkui.lint",
    "module": "lib_lint_base",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fj7ytzvpv5cofero4poh33iriu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib_lint_base-1.0.3.jar",
          "url": "lib_lint_base-1.0.3.jar",
          "size": 32414,
          "sha512": "88b14431fd9b0fd3b2158d143a17c80376aa78a80b851753bd8a037fa6d372663b0a74bc0db1043411ddbcbac81dba25fb191cc6451e655cba9a71fb8b87e219",
          "sha256": "69e96fa5740828a593e7b2b7b9bce5c5736cb0c4a3ca0f89d8f18fed9b39eaac",
          "sha1": "2b9079b56df1ae2c3095d9ac259394cec8299344",
          "md5": "00d8b660cd841dfaacf5af99ef13fff4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "lib_lint_base-1.0.3.jar",
          "url": "lib_lint_base-1.0.3.jar",
          "size": 32414,
          "sha512": "88b14431fd9b0fd3b2158d143a17c80376aa78a80b851753bd8a037fa6d372663b0a74bc0db1043411ddbcbac81dba25fb191cc6451e655cba9a71fb8b87e219",
          "sha256": "69e96fa5740828a593e7b2b7b9bce5c5736cb0c4a3ca0f89d8f18fed9b39eaac",
          "sha1": "2b9079b56df1ae2c3095d9ac259394cec8299344",
          "md5": "00d8b660cd841dfaacf5af99ef13fff4"
        }
      ]
    }
  ]
}
