{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jianghongkui.lint",
    "module": "lib_lint_client_v3_3",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xpu7ub5i45guplxagemmwqh2i4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib_lint_client_v3_3-1.0.0.jar",
          "url": "lib_lint_client_v3_3-1.0.0.jar",
          "size": 19266,
          "sha512": "cd92141ee416af61976453790f3f1d1f9c9c875597b3709ffa3b3bed8e5c316a56374f08f9a4dfd47f3963ce6cdffe5178c0960be08e8132666553de1269ee85",
          "sha256": "00494028c5f23432d42cb34763baf39f92119e6ca58db2cc4853c404cfbc6264",
          "sha1": "680f822f12df3c75b5934afdd20f94e99d6eef74",
          "md5": "21d33c5a34285f856d16f1e5a5aaca33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "lib_lint_client_v3_3-1.0.0.jar",
          "url": "lib_lint_client_v3_3-1.0.0.jar",
          "size": 19266,
          "sha512": "cd92141ee416af61976453790f3f1d1f9c9c875597b3709ffa3b3bed8e5c316a56374f08f9a4dfd47f3963ce6cdffe5178c0960be08e8132666553de1269ee85",
          "sha256": "00494028c5f23432d42cb34763baf39f92119e6ca58db2cc4853c404cfbc6264",
          "sha1": "680f822f12df3c75b5934afdd20f94e99d6eef74",
          "md5": "21d33c5a34285f856d16f1e5a5aaca33"
        }
      ]
    }
  ]
}
