{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jianghongkui.lint",
    "module": "lib_lint_client_v3_2",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xpu7ub5i45guplxagemmwqh2i4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lib_lint_client_v3_2-1.0.0.jar",
          "url": "lib_lint_client_v3_2-1.0.0.jar",
          "size": 32116,
          "sha512": "82de97cef8097e44a2b1cc3e3b4cb9615d411223639d8fca664377b6ce384ad926ec0409f10db34c3c220920363a3eedcbc1aed8ba444758ae5b58654ffcb0c2",
          "sha256": "7e2c21dce595fa1f6c062df24463dad028f4687a89f55794172540445ce9a995",
          "sha1": "f265497ededcca6f84d3b1ad9eff860a834e683e",
          "md5": "7271bbf72501118f05a191acd9c6c5fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "lib_lint_client_v3_2-1.0.0.jar",
          "url": "lib_lint_client_v3_2-1.0.0.jar",
          "size": 32116,
          "sha512": "82de97cef8097e44a2b1cc3e3b4cb9615d411223639d8fca664377b6ce384ad926ec0409f10db34c3c220920363a3eedcbc1aed8ba444758ae5b58654ffcb0c2",
          "sha256": "7e2c21dce595fa1f6c062df24463dad028f4687a89f55794172540445ce9a995",
          "sha1": "f265497ededcca6f84d3b1ad9eff860a834e683e",
          "md5": "7271bbf72501118f05a191acd9c6c5fe"
        }
      ]
    }
  ]
}
